server:
  port: 8892

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fastcampus
    username: fastcampus
    password: fast1234
    driver-class-name: org.mariadb.jdbc.Driver 
  jpa:
    database: mysql
    database-platform:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        user_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
